### ISSUE TITLE
Import postman collection

### ISSUE THREAD

**Issue by yajnasteju** [getanteon/anteon#106]
Is there a way to import postman collection to run load tests. ?

**Comment by fatihbaltaci** [comment]
Hi @yajnasteju, this feature is on our roadmap, we'll update this issue when we implement it, thanks.

**Comment by kapishmalik** [comment]
@fatihbaltaci can I work on this issue?

**Comment by fatihbaltaci** [comment]
Hi @kapishmalik, thank you. The design of this feature is not ready yet. We will start another open-source repository to convert the Postman collection to Ddosify [config format](https://github.com/ddosify/ddosify#config-file), I'll let you know when this repository is ready.

And if you have a design proposal for this feature, we can talk about it. 

Thanks.
