### ISSUE TITLE
[Feature Request]: Print out requests/s handled

### ISSUE THREAD

**Issue by douglasg14b** [getanteon/anteon#128]
When testing to see how much load an API handled before breaking, it would be nice to see a requests/s count when in non-linear mode.

Is there an existing way to get this info from the CLI tool?

**Comment by fatihbaltaci** [comment]
Hi @douglasg14b, do you want to see the **peak RPS** after the load test?

**Comment by douglasg14b** [comment]
I think seeing the request per second for each of the printed points would be helpful for non-linear tests.

Stuff at the end would be handy as well!

**Comment by fatihbaltaci** [comment]
I will add this to our roadmap. Thanks.

**Comment by douglasg14b** [comment]
Thanks!!
