### ISSUE TITLE
allow_quota option rename to allow_quote

### ISSUE THREAD

**Issue by chyde80** [getanteon/anteon#164]
The `allow_quota` option should be renamed to `allow_quote` - it's related to quote marks, not a quota(limit)

**Comment by R3gardless** [comment]
Hi @fatihbaltaci can you review these changes ? Let me know if there are any further changes needed.

**Comment by R3gardless** [comment]
Hi @fatihbaltaci, could you check if there are any further implementations needed for this issue?

**Comment by fatihbaltaci** [comment]
Hi @R3gardless, thanks for your contribution. I merged it.
