### ISSUE TITLE
How to implement custom functions?

### ISSUE THREAD

**Issue by Mikaelemmmm** [getanteon/anteon#183]
Our business interface has a custom signature algorithm, how do I do a custom algorithm function when I do a pressure testing interface

**Comment by fatihbaltaci** [comment]
Hi @Mikaelemmmm, I did not understand your use case. Please provide more details. Thanks.

**Comment by Mikaelemmmm** [comment]
For example, my back-end interface request parameters a=1&b=2, plus the signature sign is a=1&b=2&sign=xxxx , the xxxx is an encryption algorithm, I want to be able to customize this encryption algorithm when testing

**Comment by Mikaelemmmm** [comment]
Similar to postman, he can customize the signature algorithm function locally

**Comment by fatihbaltaci** [comment]
Unfortunately, custom functions are not currently supported by Ddosify. However, I have noted your request and added it to our backlog.
