### ISSUE TITLE
proxy type socks5

### ISSUE THREAD

**Issue by devnullnp** [getanteon/anteon#185]
How to use a proxy  socks4 or socks5 ?
Is there such a possibility?

**Comment by fatihbaltaci** [comment]
Hello @devnullnp, currently we only support HTTP and HTTPS proxies. I will inform you once we add support for socks proxies.

**Comment by obakeng-develops** [comment]
@fatihbaltaci I could try my hand at supporting this, if assigned.

**Comment by fatihbaltaci** [comment]
Thanks @obakeng-develops, I assigned this issue to you
