### ISSUE TITLE
How self-built ddosify is triggered in ci

### ISSUE THREAD

**Issue by Mikaelemmmm** [getanteon/anteon#228]
I want to go for automated interface testing at every ci, how do I do that? I see that the docs give ddosify cloud tutorials, but how do I do it if I'm building my own, I've noticed that self-built doesn't seem to support it

**Comment by Mikaelemmmm** [comment]
If not, are there plans to support

**Comment by fatihbaltaci** [comment]
Hi @Mikaelemmmm, the current version of Ddosify Self Hosted does not have API Support. However, we are working on releasing the Self Hosted Enterprise edition soon, which will include API support. I will keep you updated on its release.
