### ISSUE TITLE
Performance report export and purging

### ISSUE THREAD

**Issue by Allaps** [getanteon/anteon#305]
**Is your feature request related to a problem? Please describe.**
Is there any option available to export Performance report 
Is there any option available to purge old Performance report 

**Describe the solution you'd like**
Looking for any way to  purge old Performance report 

**Describe alternatives you've considered**
Looking for any way to  export and purge old Performance report 

**Additional context**

**Comment by Allaps** [comment]
Is there any option available to export Performance report
Is there any option available to purge old Performance report
Is there any option available to track and get weekly execution report

**Comment by fatihbaltaci** [comment]
Hello @Allaps, currently the features are not available. Can you send the details of your requests to support@getanteon.com so that we can plan our roadmap accordingly?

Thanks.
