### ISSUE TITLE
Gurus should Read The Fine Manpages!

### ISSUE THREAD

**Issue by linuxcaffe** [getanteon/anteon#337]
### Describe the bug

Taskwarrior Guru can't access man pages, found in repo, even though the man pages are (usually) canonical reference

### To Reproduce

 Ask the Guru something found only in the man pages, or anything about the contents of the man pages

### Expected behavior

Use the info in the man pages..

But no, the Guru can only give it's best guess what that reference might contain

### System (please complete the following information):

- OS: [e.g. MacOS]
- Anteon Version [e.g. v0.15.1]

### Additional context

Taskwarrior Guru (and all the others) should have access to the essential info in the fine man pages! Thanks!

**Comment by kursataktas** [comment]
Hey @linuxcaffe,

This repository is dedicated to Anteon rather than Gurubase. Would you mind joining the [Gurubase Discord channel](https://discord.gg/9CMRSQPqx6)?
