### ISSUE TITLE
fast, lightweight, flawless, very effective...

### ISSUE THREAD

**Issue by MademoiselleVictoire** [getanteon/anteon#39]
and has so many options! my favorite written in go. thank you so much for this! please code more like this. ddosify doesn't consume much resources, runs smooth on my smartphone without root and installation!

**Comment by MademoiselleVictoire** [comment]
//waved output for waved stress test.![20220108_130424.jpg](https://user-images.githubusercontent.com/53003138/148655029-5b520c23-4237-48bf-a2aa-724ccb044238.jpg)

**Comment by kursataktas** [comment]
Thank you @MademoiselleVictoire. We are happy to hear that Ddosify helps your daily works.
